[workspace]
preview = ["pixi-build"]
name = "rewire-custom-mappings-example"
version = "0.1.0"
description = "Custom message publishers for testing rewire dynamic mappings"
channels = ["conda-forge", "https://prefix.dev/rewire"]
platforms = ["osx-arm64", "linux-64"]

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[dependencies]
cmake = ">=4"
ninja = "*"
rewire = "*"

[feature.humble]
channels = ["robostack-humble"]

[feature.humble.dependencies]
ros-humble-ros2cli = ">=0.18.17,<0.19"
ros-humble-ros2service = ">=0.18.17,<0.19"
ros-humble-ros2topic = ">=0.18.17,<0.19"
ros-humble-ros2launch = ">=0.19.13,<0.20"
ros-humble-custom-mappings = { path = "./custom_mappings/package.xml"}

[feature.jazzy]
channels = ["robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros2cli = ">=0.32.8,<0.33"
ros-jazzy-ros2service = ">=0.32.8,<0.33"
ros-jazzy-ros2topic = ">=0.32.8,<0.33"
ros-jazzy-ros2launch = ">=0.26.11,<0.27"
ros-jazzy-custom-mappings = { path = "./custom_mappings/package.xml"}
ros-jazzy-ros2run = ">=0.32.8,<0.33"

[environments]
default = ["jazzy"]
jazzy = ["jazzy"]
humble = ["humble"]
